home-assistant/my.home-assistant.io

package.json, src-11ty/redirect-page.html, src/components/my-url-input.ts, src/const.ts, src/entrypoints/my-redirect.ts, yarn.lock
This option makes things complicated right now. Users will forget that they had it enabled and then don't realize how to turn it off (you can't uncheck the box because you are instantly redirected 😅).
I say we start without it and then move to add it later if we can come up with an improved approach. The websites are so fast now, we might not need it.
=> Remove always redirect option

src-11ty/_includes/base.html, src-11ty/index.html, src/entrypoints/my-index.ts
https://deploy-preview-14--my-home-assistant.netlify.app/
- Set correct font weight on heading
- Increase font size
- Simplify text
- Show an error when trying to configure an empty Home Assistant URL.
- Tweaks the index to differentiate between 3 use cases with each their own text:
=> Tweak index

public/.well-known/apple-app-site-association, public/.well-known/assetlinks.json, src/const.ts, src/data/instance_info.ts, src/data/is_mobile.ts, src/entrypoints/my-redirect.ts
Fix #1
~~Still need to address https://github.com/home-assistant/my.home-assistant.io/issues/1#issuecomment-774758915~~
The iOS and Android apps need to register `https://my.home-assistant.io` as a domain that will be opened by the app.
When the app is opened, they need to append `mobile=1` as a URL param. Note: some urls to my.home-assistant.io will already have URL params, you can't just blindly append `?mobile=1`.
When `mobile=1` passed, the configured Home Assistant instance is ignored and instead is set to `homeassistant://navigate`. See:
https://deploy-preview-4--my-home-assistant.netlify.app/redirect/areas/?mobile=1 
The "Open Link" button will now point at the url `homeassistant://navigate/_my_redirect/areas`. This URL should also be registered to open the mobile app. The app UI …
=> Make it work with mobile apps

src-11ty/_includes/base.html, src-11ty/_includes/base_card_with_hero.html, src-11ty/create-link.html, src-11ty/faq.html, src-11ty/index.html, src-11ty/redirect-page.html, src/entrypoints/my-index.ts, src/entrypoints/my-redirect.ts
Remove the `ha-card` from the base template, to allow simplifying the redirect JS.
This PR was originally going to include a troubleshooting text on the redirect page based on if `persisted` was set to `true` in the `pageshow` event. ~~This plan was discarded because a) browsers don't fire this reliably and b) we use `history.back()` after changing instance URL so we get a `persisted=true` then too.~~
I found a way to make it work by setting a var before navigating away.
Note that this feature only seems to reliably work on FF and Safari.
=> Clean up templating a bit and show troubleshooting

.eleventy.js, src/entrypoints/my-create-link.ts
Netlify is set up to redirect every link that doesn't end in a `/` to end with a `/`. We should make sure that all links we have end with an `/` to save on a 301.
=> Make sure we end links in /

src/entrypoints/my-create-link.ts
- Adds an HTML generator for badges.
- Adds a line of introduction for link, markdown & HTML sections, promoting where one could use it.
- Generated badges are now clickable.
=> Add HTML generator and link badges

src/entrypoints/my-create-link.ts, src/entrypoints/my-redirect.ts, src/util/validate.ts
Allow setting params for the create link screen. Only added when they are valid.
Examples:
- [With valid param](https://deploy-preview-70--my-home-assistant.netlify.app/create-link/?redirect=blueprint_import&blueprint_url=https%3A%2F%2Fgithub.com%2Fhome-assistant%2Fcore%2Fblob%2Fmaster%2Fhomeassistant%2Fcomponents%2Fautomation%2Fblueprints%2Fmotion_light.yaml)
- [With invalid param](https://deploy-preview-70--my-home-assistant.netlify.app/create-link/?redirect=blueprint_import&blueprint_url=lol%20no%20url)
=> Allow adding params for create-link

src/entrypoints/my-redirect.ts
If you use the links in the footer in the mobile app we no longer know that you are on mobile, causing problems.
We could fix those on every page, but I don't think we really need the footer on the mobile apps?
=> Hide footer in mobile apps

src-11ty/_includes/base.html
Rename in the footer "Share Link" to "Create Link". I think that with the word "Share", people might think that it relates to sharing the _current_ page, not a My link.
=> Share -> Create

src/entrypoints/my-change-url.ts, src/entrypoints/my-redirect.ts
Fixed that when we got redirected to the change password page because we hadn't configured our instance and we had parameters as part of our redirect, it would incorrectly add a `/` to the last parameter in the url.
This also changes such that changing your instance url now won't rely anymore on `history.back()` but instead just redirects to following page.
=> Fix redirecting for configuring instance adding an incorrect slash

redirect.json, src/entrypoints/my-create-link.ts
Renames the `supervisor: add-on` link to `add-on: dashboard` so it sits next to `add-on: ingress`.
Also updates the default selected link to be the first one that has no parameters such that on opening the create link page, it shows directly the buttons.
=> Rename add-on dashboard with add-on prefix

src/components/my-url-input.ts
When you need to configure your HA URL, we would ask you for your instance URL. The placeholder was set to the default url `http://homeassistant.local:8123`. If you left it empty, it would use that value, but that was not clear. Now we just fill that value in and allow users to change it.
=> Set placeholder as value

src/entrypoints/my-redirect.ts
OAuth2 callback endpoint in Home Assistant does not require authentication. Instead the authentication is contained in the state parameter which will be validated separately.
This PR will bypass the My panel for the OAuth2 callback and directly link to the AOuth2 callback endpoint in Home Assistant. This makes it work for users that do not store their login.
Fixes https://github.com/home-assistant/core/issues/73625
=> Bypass my-panel for OAuth2 callback

src/entrypoints/my-create-link.ts
While `noopener` is implied for modern browsers when `target="_blank"` is used, I added this as well for compatibility with legacy browsers.
=> Add noreferrer and noopener to sugested HTML

package.json, yarn.lock
Reverts home-assistant/my.home-assistant.io#425
Seems to cause issues as reported in #427
=> Revert "Bump lit from 3.1.1 to 3.1.2"

package.json, yarn.lock
Reverts home-assistant/my.home-assistant.io#472
Reason: #473
Caused by https://github.com/braintree/sanitize-url/pull/77
Related issue: https://github.com/braintree/sanitize-url/issues/78
=> Revert "Bump @braintree/sanitize-url from 7.0.4 to 7.1.0"

netlify.toml
Fixes #531 assuming, and this is a **big** assumption, that the production version of `my.home-assistant.io` uses Netlify. It's not documented anywhere that it _does_ but also not documented anywhere that it _doesn't_ so I gave it a try assuming it does.
```
curl -I https://my.home-assistant.io/badges/add_matter_device.svg
HTTP/1.1 200 OK
Date: Thu, 24 Apr 2025 01:54:33 GMT
Content-Type: image/svg+xml
Connection: keep-alive
Cache-Control: public,max-age=0,must-revalidate
cache-status: "Netlify Edge"; fwd=miss
etag: W/"0c195aa8984a76631d60479b98e70f73-ssl-df"
vary: Accept-Encoding
x-nf-request-id: 01JSJR1Y1BKENG0SYNM8EC98T5
CF-Cache-Status: EXPIRED
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v4?s=JrKVv2kpAiObMX0uAliA9%2BmOi4OhEeh6vJzx63GCwynOnG%2FyciWZD8RhnUjFWU …
```
=> Add cors policy header for badges

.prettierrc.json, package.json
Pretty simple change. Added a basic `format` script to `package.json` and then ran it (without any other modifications) with `yarn run format`. If y'all are ok with this change I'd be happy to add a section to the readme in a follow up PR that explains when you should run `format`.
We could also have a pre-commit that rejects changes that aren't `format`ed but I wasn't sure if that was something y'all wanted.
=> Add 'format' script

src/entrypoints/my-create-link.ts
Links with only optional params would still append a `?` to the final link.
Can be observed at https://my.home-assistant.io/create-link/?redirect=add_matter_device (which shouldn't have params, but fixing that in another PR)
See fix @ https://deploy-preview-549--my-home-assistant.netlify.app/create-link/?redirect=add_matter_device
=> Omit ? if no params

redirect.json
Matter, Zigbee and Z-Wave allowed setting optional params brand and domain. However, that data is not used in the My panel https://github.com/home-assistant/frontend/blob/dev/src/panels/my/ha-panel-my.ts#L102-L113
@bramkragten added it for Zigbee and Z-Wave, and I added it for Matter. Do you remember why Bram?
=> remove optional params from open protocol links
