home-assistant/my.home-assistant.io

script/develop, src-11ty/_includes/base.html, src-11ty/faq.html, src-11ty/index.html, src-11ty/redirect-page.html, src/components/my-instance-info.ts, src/components/my-url-input.ts, src/entrypoints/my-index.ts, src/entrypoints/my-redirect.ts, src/util/get_hass_info.ts
Query the instance to show the version on the redirect page. Requires latest nightly or 2021.3+
Querying:
Connected:
Can't connect:
Same UI shown on index page:
=> Query instance to show version

.eleventy.js, package.json, redirect.json, rollup.config.js, src-11ty/create-link.html, src/components/my-url-input.ts, src/entrypoints/my-create-link.ts, src/entrypoints/my-create-redirect.ts, src/util/search-params.ts, yarn.lock
<https://my.home-assistant.io/create-link?redirect=blueprint_import>
=> Add create link page

src-11ty/faq.html
Move the redirects down and style them nicer. Tweak a couple of FAQ answers.
https://deploy-preview-13--my-home-assistant.netlify.app/faq/
=> Make updates to FAQ

src-11ty/_includes/base.html, src-11ty/create-link.html, src/entrypoints/my-create-link.ts
- Add a link in the footer to create link
- simplify header + text
- always render the form when data is valid.
- clear input fields when changing between "import blueprint" and "set up integration"
https://deploy-preview-15--my-home-assistant.netlify.app/create-link/
=> Tweak create link

src-11ty/create-link.html, src/entrypoints/my-create-link.ts
https://deploy-preview-16--my-home-assistant.netlify.app/create-link/?redirect=areas
=> Styling tweaks on create links page

src-11ty/_includes/base.html
https://deploy-preview-17--my-home-assistant.netlify.app/
=> FIx layout to the top to prevent jumps

redirect.js, src-11ty/faq.html, src/entrypoints/my-create-link.ts
Add name to redirects and use in create link page and FAQ.
=> Add name to redirects

src/entrypoints/my-create-link.ts
Ensure "url" is capitalized to prevent this:
=> Auto capitalize "url"

redirect.js
This one has been moved to an integration dashboard and so no longer exist. I forgot and had added it 😓
=> Remove MQTT dev tool

src/entrypoints/my-create-link.ts
Fix Safari not selecting the first dropdown entry and not selecting the full text on focus of the input/textarea .
=> Fix Safari create link page

src-11ty/_includes/base.html, src-11ty/create-link.html, src-11ty/faq.html, src-11ty/index.html
Add title and descriptions to every page to improve sharing.
=> Add titles and descriptions

rollup.config.js, src-11ty/_data/manifest.js, src-11ty/_data/source.js, src-11ty/_includes/base.html, src-11ty/create-link.html, src-11ty/index.html, src-11ty/redirect-page.html, src/entrypoints/my-index.ts
Not sure how this bit of the code got lost, but this inlines the JS on every page.
=> Inline sources

src/entrypoints/my-create-link.ts
See comment: <https://github.com/home-assistant/my.home-assistant.io/pull/45#discussion_r585836270>
=> Fix generated HTML

src-11ty/_data/is_production.js, src-11ty/_includes/base.html, src/entrypoints/my-create-link.ts
- Link JS instead of embed during dev
- Fix safari footer
=> Link JS instead of embed during dev + fix safari footer

src-11ty/create-link.html, src/entrypoints/my-create-link.ts
https://deploy-preview-48--my-home-assistant.netlify.app/create-link/
=> Add confirmation to copy button

src/entrypoints/my-create-link.ts
Use redirect description as alt text.
https://deploy-preview-50--my-home-assistant.netlify.app/create-link/
=> Improve alt text of HTML/markdown badges

src-11ty/faq.html
https://deploy-preview-52--my-home-assistant.netlify.app/faq/#supported-pages
=> Show badges in the FAQ when there is enough space

src-11ty/_includes/base.html, src-11ty/index.html, src-11ty/redirect-page.html
Fixes footer on mobile devices, and some other tweaks
=> Styling fixes

.eleventy.js, package.json, yarn.lock
=> minify output in prod

src-11ty/_includes/base.html, src-11ty/index.html, src/entrypoints/my-redirect.ts
Ran our site through https://web.dev/measure/
- https://web.dev/external-anchors-use-rel-noopener/
- https://web.dev/meta-description/
- https://web.dev/html-has-lang/
=> Fix lighthouse complaints

src-11ty/_includes/base.html
=> Change link color

package.json, yarn.lock
https://github.com/11ty/eleventy/releases/tag/v0.12.0
https://github.com/11ty/eleventy/releases/tag/v0.12.1
=> Bump eleventy

src/components/my-url-input.ts, src/entrypoints/my-change-url.ts, src/entrypoints/my-create-link.ts, src/entrypoints/my-index.ts
`internalProperty` is named `state` in Lit 2.5.1 in prep of Lit 2.
=> Drop deprecated decorators

package.json, yarn.lock
=> Bump @material/mwc* to 0.21.0

package.json, src/components/my-instance-info.ts, src/components/my-url-input.ts, src/entrypoints/my-change-url.ts, src/entrypoints/my-create-link.ts, src/entrypoints/my-index.ts, yarn.lock
Upgrade to latest Lit version + Material components.
Fixes #137
Fixes #139 
Fixes #140
Fixes #141
=> Upgrade to latest lit + material

package.json, yarn.lock
We have it pinned because of a dependency conflict with mwc elemenets.
=> Bump reactive element

redirect.json, src/const.ts, src/entrypoints/my-create-link.ts
For https://github.com/home-assistant/frontend/pull/12524
=> Add optional repository URL to supervisor_addon

redirect.json
Adjusts the repairs description as suggested by @ludeeus in <https://github.com/home-assistant/my.home-assistant.io/pull/265#pullrequestreview-1058377218>
=> Adjust repairs description

README.md
Addresses #122 a bit. Not sure what direction the maintainers want to go but I want to help so I took a stab at it (as a first-time dev in this package).
=> Add development section to the readme
